parameters:
- name: name
  displayName: 'User name'
  type: string
  default: User

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello ${{ parameters.name }} !
  displayName: 'Run a one-line script'

- task: NodeTool@0 
  inputs:
    versionSpec: '11.x'

- template: templates/include-npm-steps.yml
